### ISSUE TITLE
Is it possible to change a device polling rate to 200Hz ?

### ISSUE THREAD

**Issue by kuma4321** [LordOfMice/hidusbf#122]
It's not an issue but i don't know where i can ask that question. I really like your job and i will be very glad if you can answer me.

**Comment by LordOfMice** [comment]
Yes, this was answered in link from readme but because you ask about EXACT rate I will answer more precise.
1. No, it is not possible because USB specification AND its realization restrict rates to predefined list (used in setup).
2. Controversial to 1. Yes, it is theoretically possible because you have 1000Hz in USB rates list and 200Hz is actually just the sum of 5 counts on 1000Hz. But there is one problem with zero counts in this case (they are absent).

**Comment by kuma4321** [comment]
Thanks
