### ISSUE TITLE
Zip file closes immediately after opening?

### ISSUE THREAD

**Issue by cosmicswish** [LordOfMice/hidusbf#20]
Ive tried everything and talked to a few IT peeps and they dont know how to fix it but once i extract the zip file (Ive tried to a created folder and to other areas like Documents, Pictures etc). once i click "Setup.exe" i see it open for 1-3 seconds and then it closes immediately and then the "setup.exe" will disappear not allowing me to try again.

Ive tried disabling by anti virus, clearing out all my caches, restarting computer, my internet is perfectly fine, i have a zip file opener that is popular.

Funny thing is, i used to have this file and it worked amazingly but then one day overnight it just disappeared and i havent been able to download it since which confuses the hell out of me. If you can help me correct this, i would be forever in your debt, this has caused me to quit one of my favorite games because my input delay is awful :(

**Comment by LordOfMice** [comment]
> once i click "Setup.exe" i see it open for 1-3 seconds and then it closes immediately
1. Check Windows logs (Event Viewer) for apllication crashes.
2. Do you see right elevation dialog before setup form?

>not allowing me to try again
Check is setup.exe running but invisible. Windows Task Manager or (better) Sysinternals Process Explorer

And yes, you said nothing about your operational environment like OS and its version.

P.S. It is the FIRST problem with setup.exe itself since 2005. Something VERY unusual in your system.
