### ISSUE TITLE
Is there an option available to downclock a mouse to 125Hz on hidusbf?

### ISSUE THREAD

**Issue by Joshhhuaaa** [LordOfMice/hidusbf#300]
Hi, I'm interested in downclocking my mouse to 125Hz polling rate. Currently, hidusbf seems to only allow a minimum rate of 250Hz for downclocking, and I couldn't found any methods for downclocking to 125Hz.

If you're wondering why I want to do this, it's for compatibility reasons. Some older game engines only function correctly with a mouse set to 125Hz. In the past, I could adjust this setting using the mouse manufacturer's software. However, newer mice are phasing out support for 125Hz, leaving only options like 1000/2000/4000/8000 instead. Thanks.

**Comment by LordOfMice** [comment]
> Currently, hidusbf seems to only allow a minimum rate of 250Hz for downclocking

1. For High Speed USB devices. The Low/Full Speed USB devices have 31Hz low limit. And there is such (rare) thing as USB Hub v1.x
2. It's possible to aggregate few HID reports in one with lower rate but this is outside of this software.

**Comment by Joshhhuaaa** [comment]
Thanks for the quick reply. Could you point me in the right direction for aggregating HID reports at a lower rate? Since hidusbf can't do it, is there a particular software or method you recommend?

**Comment by LordOfMice** [comment]
> Could you point me in the right direction for aggregating HID reports at a lower rate? Since hidusbf can't do it, is there a particular software or method you recommend?

Writing custom kernel mode driver or using some third party kernel mode input filtering software. Both methods require some programming skills. May be some direct solution exists by IDK it.
So using hardware solution is definitely simpler for ordinary user right now.

P.S. If you wish you can try to setup 125Hz (or lower) rate for High Speed device. 250Hz is the OFFICIAL lowest limit from MS and I did not check lower rates because I don't have High Speed USB Mouse still.
